### ISSUE TITLE
iOS NotificationServiceExtension

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Xamarin-SDK#33] opened 2017-03-11 00:04 UTC
The OneSignal 2.4.0 now uses a Notification Service Extension to display action buttons and media attachments instead of content-available.

Xamarin has built in support in creating Notifiation Exensions:
https://developer.xamarin.com/guides/ios/platform_features/introduction-to-ios10/user-notifications/enhanced-user-notifications/#Working_with_Service_Extensions

Running `sharpie` on the iOS native framework and creating instructions for setup are needed to support these OneSignal features in Xamarin.

**Comment by HectorMeneses333** [comment] 2017-06-08 22:56
When is this enhancement expected to be in production? 

Right now, if we send a notification that includes an image URL to iOS and our app is not either in the background/foreground then the notification does not display at all. However, if we send a notification with no image URL, the notification is received, badges are incremented and we can open our app even if it is not in the foreground/background. 

Our app delivers notifications for real estate, so an image of the property that we are alerting the user about is very important. 

Sincerely,
Hector

**Comment by neooleg** [comment] 2017-10-31 20:23
Guys,

do you have ETA for this update?

It become much more critical because on iOS 11 push **doesn't show at all** if it contains at least one button.

P.S.  4-5 months ago it was the same for iOS 10 as @HectorMeneses333 mentioned. However, then I assumed it was fixed because push shows on iOS 10 with buttons.

**Comment by landrzz** [comment] 2017-11-01 13:21
@neooleg  I have an iPad running iOS 11.1 beta 5 and it DOES receive the notifications with buttons.
However, none of my devices on 11.0.3 get them.

Maybe it will resolve itself when 11.1 comes out...?

**Comment by neooleg** [comment] 2017-11-01 20:39
@landrzz it might be resolved as mentioned [here](https://stackoverflow.com/questions/44796613/silent-pushes-not-delivered-to-the-app-on-ios-11).

Anyway, it should be fixed within OneSignal SDK because we can't rely on it otherwise with the next iOS version.

**Comment by neooleg** [comment] 2017-11-12 17:49
Tested on iOS 11.1.

I sent a push with button from OneSignal's web interface -- the problem is still here **if the app was swiped out**. Hence, this is not a reliable solution.

**Comment by rgomezp** [comment] 2019-04-09 18:08
Closing. Issue still internally under consideration
--

**Closed by rgomezp** 2019-04-09 18:08 UTC
Labels: Enhancement
