### ISSUE TITLE
Xamarin.iOS prompt for application settings is closed immediately

### ISSUE THREAD

**Issue by skir** [OneSignal/OneSignal-Xamarin-SDK#269] opened 2022-01-31 12:14 UTC
**Description:**

I have implemented "soft" notifications prompt using In-App message. At first show, when user clicks button in the in-app message, the system dialog appears asking for notification permission. If user has denied this prompt, or later disabled notifications through application settings, my app will show the same in-app message asking for notification permission. When user clicks again on the button in the message, I see that the dialog asking for opening application settings is presented, but it disappears in fraction of a second. It looks like it is dismissed when the fade-out animation in the in-app message is completed.

**Environment**

1. Com.OneSignal 3.10.6
2. iOS: 15.2

**Steps to Reproduce Issue:**

1. Implement "soft-prompting" for notification permissions
2. Deny system prompt for notifications or disable notifications in app settings
3. When in-app message is shown second (and consecutive times) try to accept prompt to open application settings.

**Comment by tanaynigam** [comment] 2022-05-24 16:33
@skir We have a release [OneSignalSDK.Xamarin-4.0.0](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.0.0) in which I was unable to reproduce this issue.
Please note that we have changed the package name and namespace for the SDK from `Com.OneSignal` to `OneSignalSDK.Xamarin` and would require you to remove the previous package name and add the new package name to import the SDK in your code.

Additionally, when searching for the package on nuget.org, you will be required to search for [OneSignalSDK.Xamarin](https://www.nuget.org/packages/OneSignalSDK.Xamarin/4.0.0) to import the package

closing this issue for now. Please re-open if the issue still exists

**Closed by tanaynigam** 2022-05-24 16:33 UTC
