### ISSUE TITLE
Android - HandleNotificationOpened not firing when cold started from a notification

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Xamarin-SDK#49] opened 2017-08-11 03:02 UTC
The HandleNotificationOpened handler does not fire if the app is cold started from opening a notification on Android. May only be an issue with a Xamarin Forms project. No issues on iOS in this case.

**Comment by bprochniak** [comment] 2017-11-22 07:29
The same here. The HandleNotificationOpened handler works fine when the app is running but not when is cold started.

**Comment by thefex** [comment] 2017-12-07 14:57
The proper way to fix is to use .PendingIntent at notification level (and this is the only one reliable way (AFAIK) of handling cold start on Android)
The problem is that you already said ExtenderService won't be available in Xamarin.
The explanation with mono runtime is complete non-sense (wtf) -> you are limiting functionality of the library - sure there is overhead but if you can spot VISIBLE difference between non-mono runtime version I owe you can of beer.

For those who wants to handle it properly - I am creating fork with NotificationExtendedService.

**Comment by thefex** [comment] 2017-12-08 13:09
@jkasten2 you should merge my commit to restore NotificationExtendedService:
https://github.com/thefex/OneSignal-Xamarin-SDK/commit/0f42e02cbf1d26c4c79d3695af35e38e97e9cfe1

**Comment by Nightsd01** [comment] 2018-03-31 01:11
I've been testing this issue with multiple devices/versions of Android and this bug must have been fixed in a recent SDK update because it no longer occurs.

(Also tested in iOS as well and everything looks good there too)

**Comment by Nightsd01** [comment] 2018-03-31 01:11
@jkasten2

**Closed by Nightsd01** 2018-03-31 01:11 UTC
