### ISSUE TITLE
OneSignal MAUI Support for Push Notification

### ISSUE THREAD

**Issue by aokocax** [OneSignal/OneSignal-Xamarin-SDK#281] opened 2022-03-21 12:07 UTC
There are 2 months left to GA (General Availability), but there is no push notification library working on the MAUI side.

I am trying to implement OneSignal to my MAUI project but when I try to build I am getting this error. 

![image](https://user-images.githubusercontent.com/1059475/159257497-07aa679f-20af-44f5-8fc6-006c7e4956e3.png)

When I compile the project myself and include it in the project without installing it from nuget, the above error goes away, but I get this error.

![image](https://user-images.githubusercontent.com/1059475/159257573-9b6e3849-3ead-4935-bcb5-14781d3b1558.png)

I would be very grateful if you could help in any way.

**Comment by excellapay** [comment] 2022-05-13 00:59
Any word on the MAUI Roadmap. i am currently re-coding an app from FORMS to Maui.

**Comment by jmadler** [comment] 2022-05-13 01:27
Yep!  Now that Xamarin supports MAUI, we'll start digging into MAUI support within the next couple weeks.  It will likely land after the MAUI GA unfortunately.

**Comment by pierrebrito** [comment] 2022-06-02 14:29
Hi @jmadler !
When will support for Maui launch?
Please don't leave this project behind. It's very important to us.

**Comment by meps007007** [comment] 2022-06-18 09:26
Any news on Maui support?

**Comment by mike242529** [comment] 2022-06-29 15:59
We need the OneSignal Maui nuget upgrade too. Any new news or roadmap for it?

**Comment by tanaynigam** [comment] 2022-06-29 20:34
We are currently working on a Xamarin OneSignal SDK release with MAUI support. Recent updates on MAUI support have pushed back our release. We should have a Xamarin OneSignal SDK update with MAUI support shortly.

**Comment by ilmian** [comment] 2022-07-04 04:36
We just migrated our production app from Xamarin to Maui. OneSignal had been a great feature for us in Xamarin and now that we have used to Maui, this is the only thing holding us back from going live. Please take a look at this on priority as a lot of apps are being migrated to .Net Maui. Thanks

**Comment by ZahidMehmoodquarterpi** [comment] 2022-07-04 04:56
We migrated our production app from Xamarin Forms to .Net Maui. And we are wondering from a week and half to use OneSignal with .Net Maui but so far we didn't find any luck. Please take a look to support One Signal with .Net Maui as we are not able to go live without OneSignal.

**Comment by excellapay** [comment] 2022-07-21 01:47
Any update on MAUI.  We created the new version of the App from scratch and made it like our Xamerin Forms version, but no luck. Any ETA?

**Comment by ahmadpasha7798** [comment] 2022-07-28 06:33
Any update?
We developed the app in MAUI and One-Signal sdk plays a big part in one of its features but its on hold because of this issue.
Hoping we could get an ETA? so that we could manage app release schedule accordingly.

**Comment by asafgo** [comment] 2022-08-04 06:03
Hi @jmadler 
Any update on SDK for MAUI please?

**Comment by jkasten2** [comment] 2022-08-05 09:02
@asafgo @ahmadpasha7798 @excellapay @ZahidMehmoodquarterpi @ilmian @mike242529 @meps007007 @pierrebrito @aokocax 
We have released a OneSignalSDK.Xamarin 4.2.0-beta1 version you now use.
https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.2.0-beta1-maui-only

**Comment by ahmadpasha7798** [comment] 2022-08-05 11:56
@jmadler @tanaynigam @jkasten2  
Thanks for the pre-release

I tried the sample code from the repository, but the OneSignal is not being resolved for android.
Screenshots are attached.
![Screenshot (2)](https://user-images.githubusercontent.com/73205785/183072462-e2322689-bd0a-4ea0-bc07-f8c54917edf2.png)
![Screenshot (1)](https://user-images.githubusercontent.com/73205785/183072468-1a7c2bc4-7be8-48ff-872e-e8bb8a1559bd.png)
d

**Comment by pierrebrito** [comment] 2022-08-05 13:10
@jkasten2 Thanks! We look forward to it.
Wouldn't it be interesting to make it available in another package? OneSignalSDK.Maui

**Comment by jkasten2** [comment] 2022-08-05 20:03
> I tried the sample code from the repository, but the OneSignal is not being resolved for android.
Screenshots are attached.

@ahmadpasha7798 We haven't update the sample app as part of this repo for MAUI, to test you will need to use your own project.

> @jkasten2 Thanks! We look forward to it.
Wouldn't it be interesting to make it available in another package? OneSignalSDK.Maui

We are planning to keep the same package name as OneSignalSDK.Xamarin for now, where the same package will support both Xamarin (.NET 5) and MAUI (.NET 6) in the same package.

**Comment by jrahma** [comment] 2022-08-18 19:52
Where can I find the OneSignal for MAUI setup guide?

**Comment by andrei25f** [comment] 2022-09-06 06:28
Our team followed the Xamarin SDK Setup guide.
We installed OneSignalSDK.Xamarin (4.2.0-beta1-maui-only) and ran into a number of errors:
  - Check for conflicting plugins and make sure "com.google.android.gms.version" is in your AndroidManifest.xml.
  - unknown error getting fcm token
  - No Push Token
  - Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval

It looks like the error found in the logs was the cause:
  - FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.

The solution was to install the Xamarin.Firebase.Messaging package (123.0.7)

**Comment by fhboswell** [comment] 2022-09-09 22:57
> Where can I find the OneSignal for MAUI setup guide?


> Our team followed the Xamarin SDK Setup guide. We installed OneSignalSDK.Xamarin (4.2.0-beta1-maui-only) and ran into a number of errors:
> 
> * Check for conflicting plugins and make sure "com.google.android.gms.version" is in your AndroidManifest.xml.
> * unknown error getting fcm token
> * No Push Token
> * Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
> 
> It looks like the error found in the logs was the cause:
> 
> * FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
> 
> The solution was to install the Xamarin.Firebase.Messaging package (123.0.7)

@jrahma  @andrei25f We are working on resolving these issues and supporting MAUI.

**Comment by fhboswell** [comment] 2022-11-02 18:45
@jrahma @andrei25f @pierrebrito @ahmadpasha7798 @ZahidMehmoodquarterpi @aokocax @asafgo
We now have MAUI / .Net 6 support. Please see our new [Nuget](https://www.nuget.org/packages/OneSignalSDK.DotNet).

**Closed by fhboswell** 2022-11-02 18:45 UTC
Labels: Enhancement / Feature, Compatibility Issue

**Comment by jrahma** [comment] 2022-11-18 22:40
> @jrahma @andrei25f @pierrebrito @ahmadpasha7798 @ZahidMehmoodquarterpi @aokocax @asafgo We now have MAUI / .Net 6 support. Please see our new [Nuget](https://www.nuget.org/packages/OneSignalSDK.DotNet).

But you still don't have MAUI when as a Platform when creating a new Project and we just need to use Xamarin.
