### ISSUE TITLE
Xamarin Forms app doesn't go sleep on iOS when OneSignal is present?

### ISSUE THREAD

**Issue by rudyryk** [OneSignal/OneSignal-Xamarin-SDK#14] opened 2016-09-24 06:45 UTC
I noticed that Xamarin.Forms application on iOS doesn't invoke "sleep" / "resume" events when it's being opened / closed if OneSignal is added to a project.

This is kind of unexpected behavior because some events may be tied to "resume" event - when a user opens the application again. So with OneSignal added to the project we can't detect if the user opened or closed the app. So now we can detect only an initial application launch.

**Comment by jkasten2** [comment] 2016-10-07 00:33
@rudyryk We are in the process of updating our Xamarin SDK to use our new 2.0 native SDK which may fix this issue once it is released.

You can take a look at the issue below that may provide a work around for you in the mean time.
https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/7

**Comment by rudyryk** [comment] 2016-10-07 09:00
@jkasten2 thanks for the hint!

I've added such methods to the `AppDelegate` class:

```
[Export ("oneSignalApplicationDidBecomeActive:")]
public void OneSignalApplicationDidBecomeActive (UIApplication application)
{
    Debug.WriteLine ("OneSignalApplicationDidBecomeActive");
}

[Export ("oneSignalApplicationDidEnterBackground:")]
public void OneSignalApplicationDidEnterBackground (UIApplication application)
{
    Debug.WriteLine ("OneSignalApplicationDidEnterBackground");
}
```

What I see is `OneSignalApplicationDidBecomeActive ` is invoked,  but `OneSignalApplicationDidEnterBackground ` is not!

And I can see debug output from network requests from my application after going to iPhone's home screen when the app should be in the background mode.

That actually means that my chat connection is still active and I actually receive chat messages in the background mode and my app thinks it's in the foreground. It's not intended - I'd expect a WebSocket connection to be closed, so a server could decide either send a push notification or not.

**Comment by rudyryk** [comment] 2016-10-07 12:58
Aha! The `oneSignalApplicationWillResignActive :` method did the trick! :)

```
[Export ("oneSignalApplicationWillResignActive:")]
public void OneSignalApplicationWillResignActive (UIApplication application)
{
    Debug.WriteLine ("OneSignalApplicationWillResignActive");
}
```

**Comment by jkasten2** [comment] 2017-02-22 02:33
Closing issue, this is a duplicate of issue https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/7

**Closed by jkasten2** 2017-02-22 02:33 UTC
