### ISSUE TITLE
IOS foreground display notification although InFocusDisplaying(OSInFocusDisplayOption.None)

### ISSUE THREAD

**Issue by arickatz** [OneSignal/OneSignal-Xamarin-SDK#112] opened 2018-09-04 14:08 UTC
**Description:**
IOS foreground display notification,
 although InFocusDisplaying(OSInFocusDisplayOption.None)

**Environment**
Xamarin Forms problem only happens on iOS devices
1. What version of the Xamarin SDK are you using? .NetStandard 2.0.3
2. How did you add the SDK to your project = nuget

**Steps to Reproduce Issue:**

  Example:

regular forms project using .netstandard 
sending a notification from a device and a popup is displayed when in foreground

OneSignal.Current.StartInit(ONESIGNALID)
                    .InFocusDisplaying(OSInFocusDisplayOption.None)
                    .Settings(new Dictionary<string, bool>() {
                        { IOSSettings.kOSSettingsKeyAutoPrompt,false },
                        { IOSSettings.kOSSettingsKeyInAppLaunchURL, false } })
                    .HandleNotificationOpened(HandleNotificationOpened)
                    .HandleNotificationReceived(HandleNotificationReceived)
                    .EndInit();

**Comment by MarcoRossi1960** [comment] 2019-04-04 13:26
Hi, rgomezp. Did you get any solution to this issue?

**Comment by arickatz** [comment] 2019-04-04 13:28
I got everything working as expected don’t remember what was the solution.

**Comment by rgomezp** [comment] 2019-04-18 17:10
@MarcoRossi1960 & all,
Are you seeing the same issue? I will close it for now unless anyone requests I reopen. Thanks

**Comment by softsan** [comment] 2019-07-18 20:26
I have the same issue. @MarcoRossi1960 - How did you fixed that? 
@rgomezp - any suggestion on how to fix this?

**Comment by rgomezp** [comment] 2019-07-18 20:46
Could you please include your logs? Make sure to turn on the `setLogLevel` OneSignal method.

1) Open XCode
2) Window > Devices + Simulators
3) Select device on the left
4) Press "open console" button
5) Select "all messages" (top left)
6) Reproduce issue with the connected device
7) Copy logs here

**Comment by softsan** [comment] 2019-07-18 21:18
default	02:42:19.918738 +0530	MyAppiOS	VERBOSE: onesignalUserNotificationCenter:willPresentNotification:withCompletionHandler: Fired!
default	02:42:19.946416 +0530	MyAppiOS	VERBOSE: HTTP Request (OSRequestSubmitNotificationOpened) with URL: https://onesignal.com/api/v1/notifications/134807cd-2114-402b-9bd7-1f9dca02347e, with parameters: {
  "opened" : true,
  "app_id" : "717405d2-ca40-4169-8ee4-8d25a446724c",
  "player_id" : "16062411-5c7f-4a2d-89a9-78de09441e33"
}
default	02:42:19.986832 +0530	MyAppiOS	VERBOSE: oneSignalRemoteSilentNotification:UserInfo:fetchCompletionHandler:
default	02:42:49.516273 +0530	MyAppiOS	VERBOSE: OneSignalUNUserNotificationCenter setOneSignalUNDelegate Fired!
default	02:43:08.627124 +0530	MyAppiOS	VERBOSE: onesignalUserNotificationCenter:willPresentNotification:withCompletionHandler: Fired!
default	02:43:08.649217 +0530	MyAppiOS	VERBOSE: HTTP Request (OSRequestSubmitNotificationOpened) with URL: https://onesignal.com/api/v1/notifications/9e3d1e12-23bf-4aee-baf9-d8db308dad76, with parameters: {
  "opened" : true,
  "app_id" : "717405d2-ca40-4169-8ee4-8d25a446724c",
  "player_id" : "16062411-5c7f-4a2d-89a9-78de09441e33"
}
default	02:45:00.383327 +0530	MyAppiOS	VERBOSE: HTTP Request (OSRequestSendLocation) with URL: https://onesignal.com/api/v1/players/16062411-5c7f-4a2d-89a9-78de09441e33, with parameters: {
  "app_id" : "717405d2-ca40-4169-8ee4-8d25a446724c",
  "loc_bg" : false,
  "loc_acc_vert" : 10,
  "lat" : 22.993025567835431,
  "net_type" : 0,
  "loc_acc" : 65,
  "long" : 72.538552756448766
}

**Comment by softsan** [comment] 2019-07-19 16:51
Any updates on this?

**Comment by softsan** [comment] 2019-07-22 17:14
@rgomezp - Any updates on this?

**Comment by jkasten2** [comment] 2019-07-25 03:55
@softsan Just to confirm, you have `.InFocusDisplaying(OSInFocusDisplayOption.None)` set to prevent all notifications from when your app is currently in use?

Can you double check you are not inlitizing OneSignal more than once anywhere in your app's code?

Do you see the issue any other time other then when a picture is select / taken and then going back to your app as you noted? Such as put the app in the background and coming back?

Do you have any other notification plugins or other plugins that may display notifications?

Can you reproduce the issue in an example project and share it with us?

**Comment by softsan** [comment] 2019-08-03 19:09
Can you double check you are not inlitizing OneSignal more than once anywhere in your app's code? - **Yeh i double checked that and its only initialize only once.**

Do you see the issue any other time other then when a picture is select / taken and then going back to your app as you noted? Such as put the app in the background and coming back? - **Its only happend when i select/take picture. Doesn't happen if i just put my app in background.**

Do you have any other notification plugins or other plugins that may display notifications? - Yes ToastPlugin [https://github.com/EgorBo/Toasts.Forms.Plugin](url)

Can you reproduce the issue in an example project and share it with us? - its not possible to prepare sample for reproducing

**Comment by rgomezp** [comment] 2019-08-05 19:00
Hello @softsan ,
Could you please try removing the ToastPlugin temporarily and re-testing?

**Comment by softsan** [comment] 2019-08-24 20:16
@rgomezp - I tried removing ToastPlugin but it has same issue.

**Comment by rgomezp** [comment] 2019-11-07 22:47
Apologies for the delay. I'm assuming this is no longer an issue since there hasn't been further activity. Please request it be reopened if you would like

**Closed by rgomezp** 2019-11-07 22:47 UTC
Labels: Bug: Not OneSignal, Help Wanted

**Comment by softlion** [comment] 2020-04-05 04:40
@rgomezp i repro the issue.

It happens only with specific notifications.

Is there a simpler way than to find a workaround, a return value in HandleNotificationReceived to set to disable the display of the notification ? Liek setting a property on the received notification object ?

**Comment by softlion** [comment] 2020-04-05 06:48
I've changed to OSInFocusDisplayOption.Notification, as None won't disable any onesignal notification. This really does not work.
