### ISSUE TITLE
[App Crash] java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getStableInsetBottom()' on a null object reference

### ISSUE THREAD

**Issue by srdmnc** [OneSignal/OneSignal-Xamarin-SDK#174] opened 2019-11-25 07:45 UTC
**Description:**
App crashes on startup.

**Environment**

1. 3.5.0
2. Nuget

**Steps to Reproduce Issue:**

  1. Add version 3.5.0 of the Xamarin SDK to your project
  2. Initialize the SDK with your App ID
  3. Attempt to receive a push notification

**Stacktrace:**

`
Xamarin Exception Stack:
Java.Lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getStableInsetBottom()' on a null object reference
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <a2ed8a7be0d54cc3be3352e45620f444>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <a2ed8a7be0d54cc3be3352e45620f444>:0
  at Android.App.Activity.OnResume () [0x0000a] in <289b3bcebe4a45bb839a63d61f5b11db>:0
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnResume () [0x00000] in <ba0773091df94a579a45d99874fbdec8>:0
  at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <289b3bcebe4a45bb839a63d61f5b11db>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.13(intptr,intptr)
  at java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getStableInsetBottom()' on a null object reference
  at com.onesignal.OSViewUtils.getWindowHeightAPI23Plus()
  at com.onesignal.OSViewUtils.getWindowHeight()
  at com.onesignal.WebViewManager.getWebViewMaxSizeY()
  at com.onesignal.WebViewManager.setWebViewToMaxSize()
  at com.onesignal.WebViewManager.access$700()
  at com.onesignal.WebViewManager$5.run()
  at com.onesignal.OSViewUtils$1$1.available()
  at com.onesignal.ActivityLifecycleHandler.setCurActivity()
  at com.onesignal.ActivityLifecycleHandler.onActivityResumed()
  at com.onesignal.ActivityLifecycleListener.onActivityResumed()
  at android.app.Application.dispatchActivityResumed(Application.java:214)
  at android.app.Activity.onResume(Activity.java:1217)
  at android.support.v4.app.FragmentActivity.onResume()
  at md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.n_onResume(Native Method)
  at md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.onResume()
  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1274)
  at android.app.Activity.performResume(Activity.java:6350)
  at android.app.Activity.performResume(Activity.java:6690)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3338)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3388)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:5790)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1015)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
`

**Affected Devices:**
ASUS Zenfone 2 Laser (ASUS_Z00LD)
Vivo Phone - Vivo 1606
Vivo Phone - Vivo 1601

**Comment by rgomezp** [comment] 2019-12-06 20:22
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/896

**Closed** 2019-12-06 20:23 UTC
