### ISSUE TITLE
Android device marked "not subscribed" on push send with 3.10.6 Visual Studio 2022

### ISSUE THREAD

**Issue by Dipannita20** [OneSignal/OneSignal-Xamarin-SDK#280] opened 2022-03-17 09:34 UTC
**Description:**
On Pixel 3XL(android 12), not receiving push notification on building VS 2022, device record get marked as "not subscribed" on notification send.

Build:
Build started.
Found Java SDK version 11.0.12.
Found Java SDK version 11.0.12.
Dex Fast Deployment Enabled: False
MonoAndroid Tools: C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\Android\
Android Platform API level: 30
TargetFrameworkVersion: v11.0

In the attached logcat player id is "ef0a7794-93c3-11ec-8926-ee555615cba6", however in the portal I could not find same payer id. Also there are lots of errors. Please check device logcat attached.

**Environment**
Microsoft Visual Studio Professional 2022
Version 17.1.1
VisualStudio.17.Release/17.1.1+32228.430
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Azure App Service Tools v3.0.0   17.1.358.51495
Azure App Service Tools v3.0.0

C# Tools   4.1.0-5.22109.6+0c82c4114a4e4b8b723b915eee3b13261db6717f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Visual Basic Tools   4.1.0-5.22109.6+0c82c4114a4e4b8b723b915eee3b13261db6717f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.1.0.309 (d17-1@3f96c58)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.2.0.4 (d17-1/19b97b7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a5d1934
    Java.Interop: xamarin/java.interop/d17-1@7ac33610
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.1@0893b3b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

Xamarin.iOS and Xamarin.Mac SDK   15.6.0.3 (caa899d24)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
 -->

**Steps to Reproduce Issue:**

1. Install app with 3.10.6 OneSignal SDK integrated
2. Open the app
3. Observed device record added to OneSignal portal
4. Add the record to Test User
5. Send push from OneSignal Portal to Test User
6. Wait, no notification received
7. Observed on OneSignal Portal device marked as "Not Subscribed"

![image](https://user-images.githubusercontent.com/68427594/158777582-597891a8-132d-4a82-bb71-d8f687fc7604.png)

**Anything else:**
Xamarin Forms 5.0.0.2125 installed

[logcat_onesignal_not_subscribed.txt](https://github.com/OneSignal/OneSignal-Xamarin-SDK/files/8283439/logcat_onesignal_not_subscribed.txt)

**Comment by tanaynigam** [comment] 2022-05-24 18:15
@Dipannita20 We have a release [OneSignalSDK.Xamarin-4.0.0](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.0.0) where this should no longer be an issue.

It is possible that the issue is caused due to GCM receiver not being set properly. In our new implementation of the Xamarin OneSignal SDK, we are automatically setting up the GCM receiver.

Please note that we have changed the package name and namespace for the SDK from `Com.OneSignal` to `OneSignalSDK.Xamarin` and would require you to remove the previous package name and add the new package name to import the SDK in your code.

Additionally, when searching for the package on nuget.org, you will be required to search for [OneSignalSDK.Xamarin](https://www.nuget.org/packages/OneSignalSDK.Xamarin/4.0.0) to import the package

closing this issue for now. Please re-open if the issue still exists

**Closed by tanaynigam** 2022-05-24 18:15 UTC
