### ISSUE TITLE
SendTags, DeleteTags, etc. with feedback

### ISSUE THREAD

**Issue by ArgusMagnus** [OneSignal/OneSignal-Xamarin-SDK#131] opened 2019-01-18 07:08 UTC
Could you please provide versions of the fire-and-forget methods like SendTags, DeleteTags, etc. which provide feedback when and how (successful/unsuccessful) they complete? Either with a callback or (preferrably) as `Task` (async method).

We use tags for audience targeting/filtering. Users can toggle certain tags themselves on the settings page. Not knowing if and when modifying tags succeeded makes it impossible to provide a good UI. Especially on iOS it can take a very long time (up to minutes!) before the tags are changed and the new filtering takes effect and sometimes they are not changed at all.

**Comment by Nightsd01** [comment] 2019-01-18 19:12
@ArgusMagnus The issue is that some app developers abuse `sendTags` and essentially use it as a datastore for their app, and as a result they call `sendTags` *way* too often. Because of this, we usually batch calls to `sendTags`. This means that any given call to sendTags can take up to 5 seconds.

Because of this, we do NOT recommend blocking/updating any user facing UI in your app as a result of any call to `sendTags`.

**Comment by ArgusMagnus** [comment] 2019-01-19 08:59
@Nightsd01 why was this closed, it's in no way resolved.. 

The issue is not (mainly) the time it takes (although it seems to take way longer than 5 seconds sometimes), the issue is that I don't know when or even if the operation finished.
I'm not gonna block the UI, just provide a visual indication.

Note that I cannot simply keep an internal state and assume that sendTags always does the job eventually, because sometimes it fails and then there's a discrepancy between the internal state and the tags on the OneSignal server. That's what I did initially until customers started reporting problems.

Also, the long delay only happens on iOS, on Android it's fast. This behavior does not seem to be in alignment with the reasoning you provided.

**Comment by ArgusMagnus** [comment] 2019-01-29 10:41
Am I correct in assuming that you are not considering this a real issue and wont fix this in the long run?
I found a workaround for myself, but I still consider this a serious API flaw.

**Comment by abozzelli** [comment] 2019-05-02 10:02
+1 Having a callback on the requests would be handy

**Comment by rgomezp** [comment] 2019-05-28 22:07
**Closing. Issue still internally under consideration**

**Closed by rgomezp** 2019-05-28 22:07 UTC
Labels: Enhancement/Feature
