### ISSUE TITLE
iOS - Notifications are not shown at all when Action Buttons or Media Attachments are added

### ISSUE THREAD

**Issue by qizhiyu** [OneSignal/OneSignal-Xamarin-SDK#52] opened 2017-10-26 21:36 UTC
Hi,
Just gone through this issue, and found it is already anchored at
https://documentation.onesignal.com/docs/troubleshooting-ios#section-notifications-are-not-shown-at-all-when-action-buttons-or-media-attachments-are-added 
Will there be an update shortly?

**Comment by landrzz** [comment] 2017-10-30 16:54
I can confirm I'm experiencing the same issues.

**Comment by jkasten2** [comment] 2017-10-30 18:36
@landrzz The inconsistencies you are seeing between your devices is most likely due to if you swiped your app away. It could also be an issue if you have turned off "Background App Refresh" for your app.

The list of other possible issues are listed in OneSignal's [Notification Display Issues](https://documentation.onesignal.com/docs/troubleshooting-ios#section-notification-display-issues) section.

We will update issue #33 when we have implemented the NotificationServiceExtension to fully resolve those restrictions.

**Comment by Nightsd01** [comment] 2018-04-03 00:03
The SDK now supports the NotificationServiceExtension, closing issue

**Closed by Nightsd01** 2018-04-03 00:03 UTC
