### ISSUE TITLE
Not receiving background notifications after the app has been swiped away or killed

### ISSUE THREAD

**Issue by CV-AjayDodiya** [OneSignal/OneSignal-Xamarin-SDK#265] opened 2022-01-11 11:14 UTC
**Description:**
1) I've used OneSignal to send push notifications when app is in background or swiped away or killed and signalR to receive a notification when app is foreground.
2) I do not receive notifications post 15-20 minutes when app is killed and notifications sent during those period comes altogether when I unlock my phone using power button.
3) I'm not sure if this is right approach to handle this kind of scenarios, Please guide me if I'm wrong.

**Environment**
3.10.6

Tested on devices Samsung M30s, Nokia 7.2 and MI A1

**Comment by CV-AjayDodiya** [comment] 2022-01-13 06:00
Sorry, was not aware about background or silent notifications; went through the documentation https://documentation.onesignal.com/docs/data-notifications and it is working.

**Comment by CV-AjayDodiya** [comment] 2022-01-19 13:54
You may try the below sample it happens even when I don't implement received event.
[OneSignalPush.zip](https://github.com/OneSignal/OneSignal-Xamarin-SDK/files/7897616/OneSignalPush.zip)

**Comment by jmadler** [comment] 2022-05-17 20:45
Closing as duplicate of #245

**Closed by jmadler** 2022-05-17 20:45 UTC
Labels: Possible Bug
