### ISSUE TITLE
iOS: Can't override AppDelegate methods

### ISSUE THREAD

**Issue by vsayer** [OneSignal/OneSignal-Xamarin-SDK#7] opened 2016-03-05 00:04 UTC
I'm using OneSignal service in my Xamarin iOS app, accord the documentation:

https://documentation.onesignal.com/docs/xamarin-sdk-setup

I've made all steps, BUT if i override the AppDelegate methods

OnResignActivation
DidEnterBackground
WillEnterForeground
WillTerminate
OnActivated

I'm getting the next error:

ObjCRuntime.RuntimeException: Cannot get the method descriptor for the selector 'oneSignalApplicationDidBecomeActive:' on the type 'AppDelegate', because the selector does not correspond to a method

I need to override those methods, what is my error?

Thanks!

Scraped from:  http://stackoverflow.com/questions/35761082/issue-with-onesignal-and-xamarin-ios

**Comment by digitaldoors** [comment] 2016-03-23 17:58
Has this been resolved or is there a workaround on this issue as this would prevent me from moving to OneSignal.

**Comment by g20ready** [comment] 2016-03-29 18:45
I managed to hack this by:
    [Export ("oneSignalApplicationDidBecomeActive:")]
    public void OneSignalApplicationDidBecomeActive(UIApplication application) {
        Console.WriteLine ("oneSignalApplicationDidBecomeActive:");
    }

**Comment by duckwaffle** [comment] 2016-07-15 04:51
I'm having the same issue, except when I use the hack suggested by g20ready I get the following XCode error:

Error Domain=NSCocoaErrorDomain
Code=3010 "REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION"
UserInfo={NSLocalizedDescription=REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION}

Which kills the application on startup when running via the iPhone simulator.

**Comment by mjhassan** [comment] 2016-08-10 11:05
@duckwaffle, simulator doesn't support notification, as because it involves registering device with token.  Put your OneSignal initialization code under the following condition:

    // initialize push configuration if it's not a simulator
    if (Runtime.Arch != Arch.SIMULATOR)
    {
         // your OneSignal initialization; e.g.
         //OneSignal.Init();
    }

**Comment by jkasten2** [comment] 2017-02-22 03:07
From my testing this bug is only reproducible from the simulator and does not effect real devices.

I wasn't able to find a way to include this workaround into the SDK. The following is needed in your `AppDelegate.cs` if you are overriding the listed methods which is the default for new projects.
```C#
      // The following Exports are needed to run OneSignal in the iOS Simulator.
      //   The simulator doesn't support push however this prevents a crash due to a Xamarin bug
      //   https://bugzilla.xamarin.com/show_bug.cgi?id=52660
      [Export("oneSignalApplicationDidBecomeActive:")]
      public void OneSignalApplicationDidBecomeActive(UIApplication application)
      {
         // Remove line if you don't have a OnActivated method.
         OnActivated(application);
      }

      [Export("oneSignalApplicationWillResignActive:")]
      public void OneSignalApplicationWillResignActive(UIApplication application)
      {
         // Remove line if you don't have a OnResignActivation method.
         OnResignActivation(application);
      }

      [Export("oneSignalApplicationDidEnterBackground:")]
      public void OneSignalApplicationDidEnterBackground(UIApplication application)
      {
         // Remove line if you don't have a DidEnterBackground method.
         DidEnterBackground(application);
      }

      [Export("oneSignalApplicationWillTerminate:")]
      public void OneSignalApplicationWillTerminate(UIApplication application)
      {
         // Remove line if you don't have a WillTerminate method.
         WillTerminate(application);
      }

       // Note: Similar exports are needed if you add other AppDelegate overrides.
```


I have opened a bug with Xamarin to see if they can provide a fix and / or a workaround so the the code above isn't required.

https://bugzilla.xamarin.com/show_bug.cgi?id=52660

Until then we have included this code in our documentation.

Thanks.

**Comment by jkasten2** [comment] 2017-02-22 20:02
Xamarin was able to provide a simpler work around by adding `--registrar:static` to your iOS Simulator build `Additional mtouch arguments`. More details on setting this below.
https://documentation.onesignal.com/docs/xamarin-sdk-setup#section-5-ios-optional-only-required-for-ios-simulator-builds

**Comment by jkasten2** [comment] 2017-02-22 21:04
Going to close this ticket since the flag requirement is noted in the documentation. Changes need to remove this would have to be done in the iOS native SDK.

**Closed by jkasten2** 2017-02-22 21:04 UTC
Labels: bug

**Comment by icalderond** [comment] 2020-08-20 03:04
> From my testing this bug is only reproducible from the simulator and does not effect real devices.
> 
> I wasn't able to find a way to include this workaround into the SDK. The following is needed in your `AppDelegate.cs` if you are overriding the listed methods which is the default for new projects.
> 
> ```cs
>       // The following Exports are needed to run OneSignal in the iOS Simulator.
>       //   The simulator doesn't support push however this prevents a crash due to a Xamarin bug
>       //   https://bugzilla.xamarin.com/show_bug.cgi?id=52660
>       [Export("oneSignalApplicationDidBecomeActive:")]
>       public void OneSignalApplicationDidBecomeActive(UIApplication application)
>       {
>          // Remove line if you don't have a OnActivated method.
>          OnActivated(application);
>       }
> 
>       [Export("oneSignalApplicationWillResignActive:")]
>       public void OneSignalApplicationWillResignActive(UIApplication application)
>       {
>          // Remove line if you don't have a OnResignActivation method.
>          OnResignActivation(application);
>       }
> 
>       [Export("oneSignalApplicationDidEnterBackground:")]
>       public void OneSignalApplicationDidEnterBackground(UIApplication application)
>       {
>          // Remove line if you don't have a DidEnterBackground method.
>          DidEnterBackground(application);
>       }
> 
>       [Export("oneSignalApplicationWillTerminate:")]
>       public void OneSignalApplicationWillTerminate(UIApplication application)
>       {
>          // Remove line if you don't have a WillTerminate method.
>          WillTerminate(application);
>       }
> 
>        // Note: Similar exports are needed if you add other AppDelegate overrides.
> ```
> 
> I have opened a bug with Xamarin to see if they can provide a fix and / or a workaround so the the code above isn't required.
> 
> https://bugzilla.xamarin.com/show_bug.cgi?id=52660
> 
> Until then we have included this code in our documentation.
> 
> Thanks.
Thanks bro.
